### ISSUE TITLE
Add quicksettings tile

### ISSUE THREAD

**Issue by Maxr1998** [Maxr1998/home-assistant-Android#18]
The quicksettings tile might open a dialog which shows a preconfigured set of actions, probably only supporting switch view types and sensors.

**Comment by pizzapants** [comment]
@Maxr1998 
This would be a nice feature. Until its added, you can follow my [instructions](https://github.com/pizzapants/HomeAssistant/blob/master/android.md) here to add your own (not trying to spam my setup but thought it might be helpful).

**Comment by DJaeger** [comment]
@pizzapants Is there an alternative to MacroDroid from F-Droid?

**Comment by DJaeger** [comment]
@Maxr1998 How about quicksettings within a fixed notification?

**Comment by Maxr1998** [comment]
I don't really like cluttering the notification bar with persistent notifications - a real quicksettings item fits a lot better for this task.

**Comment by DJaeger** [comment]
But that would require one click more to open the quick settings dialog, so they are not really quick anymore, or am I wrong?

**Comment by LuccoJ** [comment]
It requires two *swipes* if the quick setting is not among the first bunch which get shown directly when you make the first swipe to pull down the notification bar. If you only want to swipe once, then all you have to do is make it one of those.
Besides, Android calls them "quick settings" because it considers them to be the thing that people can access quickly, and even if it's somehow suboptimal in its choice at this time, I don't think it's an individual app's place to override that and use its own system instead.
