### ISSUE TITLE
Provide pure-floss build flavor

### ISSUE THREAD

**Issue by krt16s** [Maxr1998/home-assistant-Android#29]
Recent version added non-free dependencies, e.g. play-services from `compile "com.google.android.gms:play-services-location:10.2.4"`. Please provide a build flavor that replaces or removes this.

**Comment by grote** [comment]
Instead of using non-free software to provide location updates (yes the play services library is proprietary), you can use [Mapzen Lost](https://mapzen.com/blog/open-source-location-services-with-lost/). Then you don't even need a different flavor.

Please do not include more proprietary libraries in the future, as they make the whole project proprietary.

**Comment by Maxr1998** [comment]
We actually discussed this issue on the home asisstant Gitter before I even implemented the location updater, and came to the conclusion to use Google Play services lib as a start because of better battery life for most users and easier implementation, and provide a completely free build flavor when we hit a generally stable version, which will be very soon now.
I will definitely take a look at the Mapzen Lost library for that, as it should make the support of multiple flavors extremely easy.
